// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'weather_body.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'weather_body.g.dart';

@freezed
class WeatherBody with _$WeatherBody {
  const factory WeatherBody({
    required List<WeatherPart> weather,
    required MainPart main,
    required String name,
  }) = _WeatherBody;

  factory WeatherBody.fromJson(Map<String, Object?> json) =>
      _$WeatherBodyFromJson(json);
}

@freezed
class WeatherPart with _$WeatherPart {
  const factory WeatherPart({
    required int id,
    required String main,
    required String description,
  }) = _WeatherPart;

  factory WeatherPart.fromJson(Map<String, Object?> json) =>
      _$WeatherPartFromJson(json);
}

@freezed
class MainPart with _$MainPart {
  const factory MainPart({
    required double temp,
    @JsonKey(name: 'feels_like') required double feelsLike,
  }) = _MainPart;

  factory MainPart.fromJson(Map<String, Object?> json) =>
      _$MainPartFromJson(json);
}








// {
//    "coord":{
//       "lon":74.6062,
//       "lat":42.8376
//    },
//    "weather":[
//       {
//          "id":500,
//          "main":"Rain",
//          "description":"light rain",
//          "icon":"10n"
//       }
//    ],
//    "base":"stations",
//    "main":{
//       "temp":7.61,
//       "feels_like":6.09,
//       "temp_min":7.61,
//       "temp_max":7.61,
//       "pressure":1022,
//       "humidity":86,
//       "sea_level":1022,
//       "grnd_level":925
//    },
//    "visibility":8947,
//    "wind":{
//       "speed":2.38,
//       "deg":123,
//       "gust":3.28
//    },
//    "rain":{
//       "1h":0.4
//    },
//    "clouds":{
//       "all":100
//    },
//    "dt":1678113715,
//    "sys":{
//       "type":1,
//       "id":8871,
//       "country":"KG",
//       "sunrise":1678066226,
//       "sunset":1678107351
//    },
//    "timezone":21600,
//    "id":1528675,
//    "name":"Bishkek",
//    "cod":200
// }